AdVantageHub/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('django.contrib.auth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'blog'

urlpatterns = [
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(template_name="blog/signup.html"), name='signup'),
    path('', views.PostListView.as_view(), name='post_list'),
    path('new/', views.CreateView.as_view(), name='post_view'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('post/<int:pk>/update/', views.PostUpdateView.as_view(), name='post_update'),
    path('post/<int:pk>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
    path('dashboard/', views.PostReviewerListView.as_view(), name='dashboard'),
    # path('post/<int:pk>/<str:email>/accept/', views.AcceptView.as_view(), name = 'accept'),
    # path('post/<int:pk>/<str:email>/reject/', views.RejectView.as_view(), name = 'reject'),
    path('post/rejected/', views.PostRejectedListView.as_view(), name='rejected_post'),
    path('post/<int:pk>/delete/', views.PostDelete.as_view(), name='delete_post'),

]

blog/models.py
from django.db import models
from django.urls import reverse


class User(models.Model):
    objects = None
    username = models.CharField(max_length=50)
    email = models.EmailField()
    password = models.CharField(max_length=100)



class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)


class Comment(models.Model):
    content = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

blog/forms.py
from django.forms import ModelForm
from .models import Post, Comment
from django import forms
from django.core.exceptions import ValidationError
import datetime
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class UserCreateForm:
    def __init__(self, data=None, **kwargs):
        if data is not None:
            self.username = data.get('username')
            self.email = data.get('email')
            self.password = data.get('password')
        else:
            self.username = None
            self.email = None
            self.password = None

class PostForm:
    def __init__(self, data):
        self.title = data['title']
        self.content = data['content']
        self.user_id = data['user_id']

class CommentForm:
    def __init__(self, data):
        self.content = data['content']
        self.user_id = data['user_id']
        self.post_id = data['post_id']

blog/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import Post
from django.views.generic.edit import FormView
from .forms import PostForm,CommentForm,UserCreateForm
from . import forms
from django.utils import timezone
from django.urls import reverse_lazy,reverse
from django.views.generic import TemplateView, DetailView, CreateView, ListView, UpdateView
from django.contrib.auth.models import User
from django.views import View
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic.edit import DeleteView


class PostDelete(DeleteView):
    model = Post
    success_url = reverse_lazy('blog:post_list')

class SignUp(CreateView):
    """
    Signup of People
    """
    form_class = forms.UserCreateForm
    success_url = reverse_lazy('login')
    template_name = 'blog/signup.html'
    return render(request,'blog/signup.html')


def index(request):
    return render(request,'blog/index.html')


class CreateView(CreateView):
    """
    Create Form
    Should be available to only the editor
    """
    template_name = 'blog/form_detail.html'
    form_class = PostForm




class PostUpdateView(UpdateView):
    """
    Update the Form:
    Should be available to only the Editor
    """
    template_name = 'blog/form_update.html'
    model = Post
    form_class = PostForm
    exclude = ['rev1_status','rev2_status','rev3_status']
    success_url = reverse_lazy('blog:rejected_post')

    def get_object(self):
        """
        To update the review for 1,2,3 to default 0 value
        """
        obj = Post.objects.get(pk=self.kwargs['pk'])
        obj.rev1_status = 0
        obj.rev2_status = 0
        obj.rev3_status = 0
        return obj


class AboutView(TemplateView):
    """
    About Page
    """
    template_name = 'blog/about.html'


class PostListView(ListView):
    """
    Return the list passed by all the Reviewers
    """
    template_name = 'blog/post_list.html'
    model = Post

    def get_queryset(self):
        """
        Returns a query which is is passed by Reviewer 3
        """
        if self.request.user.is_authenticated:
            return Post.objects.filter(rev3_status__exact=1).order_by('start_date')


class PostDetailView(DetailView):
    """
    Returns the Detailed view of the Posts
    """

    template_name = 'blog/post_detail.html'
    queryset = Post.objects.all()

    def post(self, request, *args, **kwargs):
        print(self.kwargs)
        print(request.POST)
        pk=self.kwargs['pk']
        print('Start of fxns')
        add_comment_to_post(request, pk)
        # print(reverse('blog:dashboard'))
        # print(redirect('blog:dashboard'))
        return redirect('blog:dashboard')


class PostRejectedListView(ListView):
    """
    Returns a list rejected by the reviewers
    """
    template_name = 'blog/post_rejected_list.html'
    model = Post

    def get_queryset(self):
        return Post.objects.filter(rev1_status__exact=-1) | Post.objects.filter(rev2_status__exact=-1) | Post.objects.filter(rev3_status__exact=-1)


class PostReviewerListView(ListView):
    """
        Returns the Pending Post for each reviewer
    """
    template_name = 'blog/reviewer_list.html'
    model  = Post

    def get_queryset(self):
        "elif self.request.user.email == 'reviewer2@gmail.com':"
        # Gets the id of the reviewer and returns the pending ads

        if  self.request.user.email == 'reviewer1@gmail.com' :
            return Post.objects.filter(rev1_status__exact=0, rev2_status__exact=0, rev3_status__exact=0).order_by('start_date')
        elif self.request.user.email == 'reviewer2@gmail.com':
            return Post.objects.filter(rev1_status__exact=1,rev2_status__exact=0, rev3_status__exact=0).order_by('start_date')
        elif self.request.user.email == 'reviewer3@gmail.com':
            return Post.objects.filter(rev1_status__exact=1, rev2_status__exact=1, rev3_status__exact=0).order_by('start_date')
        else:
            print("User Not found")


def add_comment_to_post(request, pk):
    """
    Adds Comments to the Post
    """
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            # print(comment.author)
            # return redirect('blog:post_detail', pk=post.pk)

        user_email = request.user.email
        status = request.POST['btn_status']
        post_found = get_object_or_404(Post, id=pk)
        if user_email == 'reviewer1@gmail.com':
            post_found.rev1_status = status
            post_found.save()
        elif user_email == 'reviewer2@gmail.com':
            post_found.rev2_status = status
            post_found.save()
        elif user_email == 'reviewer3@gmail.com':
            post_found.rev3_status = status
            post_found.save()
        return redirect('blog:dashboard')


# class RejectView(View):
#
#     def post(self, request, *args, **kwargs):
#         user_email = kwargs['email']
#         post_id = kwargs['pk']
#         post_found = get_object_or_404(Post, id=post_id )
#         if user_email == 'reviewer1@gmail.com' :
#             post_found.rev1_status = -1
#             post_found.save()
#         elif user_email == 'reviewer2@gmail.com' :
#             post_found.rev2_status = -1
#             post_found.save()
#         elif user_email == 'reviewer3@gmail.com' :
#             post_found.rev3_status = -1
#             post_found.save()
#         return redirect('blog:post_list')
#         return None
#
#
# class AcceptView(View):
#
#     def post(self, request, *args, **kwargs):
#         user_email = kwargs['email']
#         post_id = kwargs['pk']
#         post_found = get_object_or_404(Post, id=post_id )
#         if user_email == 'reviewer1@gmail.com' :
#             post_found.rev1_status = 1
#             post_found.save()
#         elif user_email == 'reviewer2@gmail.com' :
#             post_found.rev2_status = 1
#             post_found.save()
#         elif user_email == 'reviewer3@gmail.com' :
#             post_found.rev3_status = 1
#             post_found.save()
#         else:
#             print('No user')
#         return redirect('blog:post_list')

templates/blog/about.html
{% extends 'blog/base.html' %}
{% block content %}
<h1>About US</h1>
<p>Thanks for visiting the site! Check all this cool stuff about the site!</p>

{% endblock %}

templates/blog/add_comment_to_post.html
{% extends 'blog/base.html' %}
{% load bootstrap3 %}
{% block content %}

  <h1>New Comment</h1>
  <form method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" name="btn btn-default">Send</button>
  </form>
{% endblock %}

templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>POST</title>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

  <script type="text/javascript">

  </script>






</head>

<body>




  <nav class="navbar navbar-default">

    <div class="container">
      <div class="container-fluid">
        <ul class="nav navbar-nav">
          <a class="navbar-brand bigbrand" href="{% url 'blog:post_list' %}">Ad management</a>

          <li><a href="{% url 'blog:about' %}">About</a></li>
          <li><a href="https://www.github.com">Github</a></li>
          <li><a href="https://www.linkedin.com">LinkedIn</a></li>
        </ul>

        <ul class='nav navbar-nav navbar-right'>
          {% if user.is_authenticated %}
          <li> <a href="{% url 'blog:post_list' %}"><span class="glyphicon glyphicon-user"></span></a></li>


          <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Welcome {{user.username}} <span class="caret"></span></a>
        <ul class="dropdown-menu">
          {% if user.is_staff %}
          <li> <a href="{% url 'blog:post_view' %}">New Post</a></li>
          <li> <a href="{% url 'blog:rejected_post' %}">Rejected Posts</a> </li>

          {% else %}
          <li> <a href="{% url 'blog:dashboard' %}">Dashboard</a> </li>
          {% endif %}
          <li><a href="{% url 'blog:logout' %}" >Log out</a></li>
        </ul>
      </li>


          {% else %}
          <li> <a href="{% url 'login' %}">Login</a></li>
          <li> <a href="{% url 'blog:signup' %}">SignUp</a></li>
          {% endif %}
        </ul>

      </div>
    </div>
  </nav>



  <div class="jumbotron">
    <div class="container">
      <h2>Ad Management System</h2>
    </div>

  </div>

  {% block content %}

  {% endblock %}



</body>

</html>

templates/blog/form_detail.html
{% extends 'blog/base.html' %}
{% block content %}
{% load bootstrap3 %}

<div class="container">
  <form method="post" action="{% url 'blog:post_view' %}" enctype="multipart/form-data" >

    {% csrf_token %}
    {% bootstrap_form  form %}


    <input type="submit" value="submit">
  </form>
</div>


{% endblock %}

templates/blog/form_update.html
{% extends 'blog/base.html' %}
{% block content %}
{% load bootstrap3 %}

<div class="container">
  <form method="post" action="{% url 'blog:post_update' post.id %}">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="submit">
  </form>
</div>


{% for comment in post.comments.all %}
    <div class="comment">
        <div class="date">{{ comment.created_date }}</div>
        <strong>{{ comment.author }}</strong>
        <p>{{ comment.text|linebreaks }}</p>
    </div>
{% empty %}
    <p>No comments here yet :(</p>
{% endfor %}


{% endblock %}

templates/blog/index.html
{% extends 'blog/base.html' %}
{% block content %}
<div class="container form-view">



</div>

{% endblock %}

templates/blog/post_confirm_delete.html
{% extends "blog/base.html" %}
{% block content %}
  <div class="container">
      <div class="jumbotron">
            <form action="" method="post">{% csrf_token %}
                <p>Are you sure you want to delete "{{ object }}"?</p>
                <input class='btn btn-danger' type="submit" value="Confirm" >
            </form>
      </div>
  </div>

{% endblock %}

templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% block content %}


<div class="container">
  <div class="jumbotron">

    <h1>{{object.title}}</h1>
        <ul>


          {% if object.start_date_pic%}
          <li> <img src="{{ object.start_date_pic.url|default_if_none:'#' }}" alt="Start Date Pic"> </li>
          {% endif %}
          <li>Start Date: {{object.start_date}}</li>
          <li>End Date: {{object.end_date}}</li>
          <li>Amount Per Day: {{object.amount_per_day}}</li>
          <li>Amount Per Month{{object.amount_per_month}}</li>
          {% if object.end_date_pic%}
          <li><img src="{{object.end_date_pic.url|default_if_none:'#'}}" alt="end date Pic"></li>
          {% endif %}
        </ul>

  </div>

</div >
<div class="container">
        {% if user.is_staff %}
        <a class="btn btn-warning" href="{% url 'blog:delete_post' pk=object.id%}">Delete?</a>
        <a class="btn btn-info" href="{% url 'blog:post_update' pk=object.id%}">Update?</a>
        {% endif %}
</div>
<br>
<br>
<!--Button to add comment  -->
{% if user.is_authenticated and not user.is_staff and not object.rev3_status %}
<div class="accept_reject_btn">


  <button class="open-button accept-button" onclick="openForm(1)" >Accept</button>

  <button class="open-button" onclick="openForm(-1)">Reject</button>
</div>
{% endif %}



<!-- comment form -->
<div class="form-popup" id="myForm">
  <form  id='popup_form' class="form-container" method="post" >
    {% csrf_token %}

    <label for="author"><b>Author</b></label>
    <input id="author" type="text" name="author" >

    <label for="text"><b>Text</b></label>
    <textarea id="text" name="text" rows="6" cols="32" placeholder="Enter text here"></textarea>

    <button type="submit" name='myntn' id='subme' class="btn">Submit</button>
    <button type="button" class="btn cancel" onclick="closeForm()">Close</button>
  </form>
</div>

<script>
function openForm(status) {
  document.getElementById("myForm").style.display = "block";
  if (status == 1){
    $('#popup_form').append('<input type="hidden" name="btn_status" value="1">')
    $('.form-popup').css('left','15px')
    $('.form-popup').css('right','inherit')
  }
  else {
    console.log('Pressed Reject btn');
    $('#popup_form').append('<input type="hidden" name="btn_status" value="-1">');
    $('.form-popup').css('right','15px');
    $('.form-popup').css('left','inherit')
  }
}

function closeForm() {
  document.getElementById("myForm").style.display = "none";
}
</script>


<!-- new comment form  -->
{% if user.is_staff %}
<div class="container">
    <div class="jumbotron">
        {% if user.is_staff %}

        <br>
        {% for comment in post.comments.all %}
        <div class="comment">
            <div class="date">{{ comment.created_date }}</div>
            <strong>{{ comment.author }}</strong>
            <p>{{ comment.text|linebreaks }}</p>
        </div>
    {% empty %}
    <p>No comments here yet :(</p>
    {% endfor %}
    {% endif %}
    </div>
</div>


{% endif %}






{% endblock %}

templates/blog/post_list.html
{% extends "blog/base.html" %}
{% block content %}


{% for post in post_list %}
<!-- {% if user.is_authenticated or post.status == True %} -->
<div class="post">
  <ul>
    <h2> <a href="{% url 'blog:post_detail' pk=post.pk %}">{{post.title}}</a></h2>
    <p>Published on: {{post.start_date|date:"D M Y"}}</p>
  </ul>
<!-- {% endif %} -->
{% endfor %}


{% endblock %}

templates/blog/post_rejected_list.html
{% extends "blog/base.html" %}
{% block content %}


{% for post in post_list %}
{% if user.is_authenticated or post.status == True %}
<div class="post">
  <ul>
    <h2> <a href="{% url 'blog:post_update' pk=post.pk %}">{{post.title}}</a></h2>
    <p>Published on: {{post.start_date|date:"D M Y"}}</p>
  </ul>
{% endif %}
{% endfor %}


{% endblock %}

templates/blog/reviewer_list.html
{% extends "blog/base.html" %}
{% block content %}


{% for post in post_list %}
{% if user.is_authenticated or post.status == True %}
<div class="post">
  <ul>
    <h2> <a href="{% url 'blog:post_detail' pk=post.pk %}">{{post.title}}</a></h2>
    <p>Published on: {{post.start_date|date:"D M Y"}}</p>
  </ul>
{% endif %}
{% endfor %}


{% endblock %}

templates/blog/signup.html
{% extends 'blog/base.html' %}
{% load bootstrap3 %}
{% block content %}

<div class="jumbotron">

    <div class="container">
      <form  method="post">
        {% csrf_token %}
        {% userCreateForm form %}
        <input type="submit" name="" value="Sign Up">
      </form>

    </div>
</div>


{% endblock %}